using System;

[Serializable]
public enum GameState
{
	START = 0,
	PLAYING = 1,
	TUTORIAL_LOOK = 2,
	TUTORIAL_MOVE = 3,
	TUTORIAL_FIRE = 4,
	TUTORIAL_RELOAD = 5,
	PAUSED = 6,
	SAVEME = 7,
	DIED = 8,
	MENU_MAIN = 9,
	MENU_UPGRADES = 10,
	MENU_GET_BLOCKS = 11,
	MENU_FREE_STUFF = 12,
	MENU_OBJECTIVES = 13,
	MENU_STATS = 14,
	MENU_SETTINGS = 15,
	MENU_MORE = 16,
	LAST_STATE = 17,
	RESET = 18,
	PAUSED_SETTINGS = 19,
	PAUSED_UPGRADES = 20,
	PAUSED_QUIT_TO_MENU = 21,
	PAUSED_RESTART = 22,
	GET_BLOCKS_QUESTION = 23,
	GET_BLOCKS_QUESTION_MENU = 24,
	INFO = 25,
	TUTORIAL_BLOCKS = 26,
	PURCHASE_SUCCESS = 27,
	NO_STORE_ACCESS = 28,
	RETRIEVING_STORE = 29,
	COUNT = 30
}
